import React, { useState, useEffect } from 'react';
import { 
  Folder, 
  FileText, 
  Database, 
  Download, 
  HardDrive, 
  Info, 
  ExternalLink, 
  FileCode,
  FileSpreadsheet,
  ChevronRight,
  Clock,
  Upload
} from 'lucide-react';

export default function DriveExplorer({ state, logs, advancedMode, theme = 'dark', searchQuery = '' }) {
  const [selectedFile, setSelectedFile] = useState(null);
  const [activeFolder, setActiveFolder] = useState('All');

  // Local state for dynamically mutable files listing
  const [filesList, setFilesList] = useState([]);
  
  // Upload Simulator States
  const [uploading, setUploading] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [uploadStep, setUploadStep] = useState('');
  const [dragActive, setDragActive] = useState(false);

  // Sync files list with global state shifts
  useEffect(() => {
    const defaultFiles = [
      {
        id: 'file-1',
        name: 'cs401_presentation_v2.pptx',
        folder: 'Deliverables',
        type: 'slides',
        size: '1.4 MB',
        updated: '10 mins ago',
        status: state === 'mitigated' ? 'READY' : 'TRIAGING',
        content: `SLIDE DRAFT - AUTOGENERATED BY OVERDRIVE AI
--------------------------------------------------
Slide 1: CS401 Project Final Sync (Triage Overview)
Slide 2: System Architecture & WebSocket Daemon
Slide 3: Interface Redesign & Dynamic Realignment
Slide 4: Verification telemetry & Test Suites
Slide 5: Conclusion & Future Scalability

* Status: Compiled with zero errors. ready for PowerPoint/Google Slides.*`
      },
      {
        id: 'file-2',
        name: 'extension_request_prof_miller.eml',
        folder: 'Drafts',
        type: 'email',
        size: '3.8 KB',
        updated: '2 mins ago',
        status: state === 'mitigated' ? 'TRANSMITTED' : 'PENDING APPROVAL',
        content: `From: student@university.edu
To: prof.miller@university.edu
Subject: Extension Request / Deadline Conflict - CS401 Presentation

Dear Professor Miller,

I am writing to formally request a 24-hour extension on the CS401 Presentation submission due to a high-priority deadline conflict. I have rescheduled my other commitments to guarantee completion by tomorrow evening.

Thank you for your understanding.

Best regards,
Autonomous Overdrive Core (Authorized Triage Mode)`
      },
      {
        id: 'file-3',
        name: 'slack_apology_thread.json',
        folder: 'Drafts',
        type: 'json',
        size: '1.2 KB',
        updated: '5 mins ago',
        status: state === 'mitigated' ? 'TRANSMITTED' : 'PENDING APPROVAL',
        content: `{
  "platform": "Slack",
  "channel": "#team-workspace",
  "message": "Team, I am running slightly behind on the slide deck compile. Apology draft transmitted to primary communication channels. Restructuring calendar slots to lock focus now.",
  "bot_override": true,
  "status": "pending_user_approval"
}`
      },
      {
        id: 'file-4',
        name: 'triage_audit_log.json',
        folder: 'Logs',
        type: 'log',
        size: '8.4 KB',
        updated: 'Just now',
        status: 'VERIFIED',
        content: JSON.stringify(logs, null, 2) || `[\n  {\n    "status": "Core Active",\n    "integrity": "100%"\n  }\n]`
      },
      {
        id: 'file-5',
        name: 'focus_lockdown_rules.conf',
        folder: 'Logs',
        type: 'config',
        size: '950 B',
        updated: '1 hour ago',
        status: 'ACTIVE',
        content: `# Overdrive Focus Lockdown Configuration
[LockdownSettings]
block_domains = twitter.com,youtube.com,reddit.com,facebook.com
mute_system_sounds = true
force_ide_launch = true
auto_accept_grace_period = 15s
focus_duration_minutes = 240`
      }
    ];

    // Preserving user uploaded files during state sync
    setFilesList(prevList => {
      const userFiles = prevList.filter(file => file.id.startsWith('user-file-'));
      return [...userFiles, ...defaultFiles];
    });
  }, [state, logs]);

  // Run upload simulator intervals
  const simulateUpload = () => {
    if (uploading) return;
    setUploading(true);
    setUploadProgress(0);
    setUploadStep('Connecting to secure upload gate...');

    const steps = [
      { progress: 15, step: 'Streaming packet blocks...' },
      { progress: 40, step: 'Injecting secure metadata...' },
      { progress: 65, step: 'Running antivirus inspect scan...' },
      { progress: 85, step: 'Compiling content parameters...' },
      { progress: 100, step: 'Verification complete! Saved to Deliverables.' }
    ];

    let currentStepIdx = 0;
    const interval = setInterval(() => {
      setUploadProgress(prev => {
        const next = prev + 5;
        
        const matchingStep = steps.find(s => next >= s.progress && s.progress > prev);
        if (matchingStep) {
          setUploadStep(matchingStep.step);
        }

        if (next >= 100) {
          clearInterval(interval);
          setTimeout(() => {
            const newFile = {
              id: `user-file-${Date.now()}`,
              name: 'cs401_slides_final.pptx',
              folder: 'Deliverables',
              type: 'slides',
              size: '2.5 MB',
              updated: 'Just now',
              status: 'READY',
              content: `DELIVERABLE ARCHIVE - TRANSMITTED VIA SECURITY UPLOAD GATE
--------------------------------------------------
File: cs401_slides_final.pptx
Folder: Deliverables
Compiled Time: ${new Date().toLocaleTimeString()}
Integrity: Validated (SHA-256 Verified)

* Contains slide deck alignment presentation slides for target review.*`
            };
            setFilesList(prevList => [newFile, ...prevList]);
            setSelectedFile(newFile);
            setUploading(false);
          }, 600);
          return 100;
        }
        return next;
      });
    }, 80);
  };

  // Filter files by folder AND search query
  const filteredFiles = filesList.filter(file => {
    const matchesFolder = activeFolder === 'All' || file.folder === activeFolder;
    const matchesSearch = searchQuery 
      ? file.name.toLowerCase().includes(searchQuery.toLowerCase()) || 
        file.content.toLowerCase().includes(searchQuery.toLowerCase())
      : true;
    return matchesFolder && matchesSearch;
  });

  const getFileIcon = (type) => {
    switch (type) {
      case 'slides': return <FileSpreadsheet className="w-9 h-9 text-[#f59e0b]" />;
      case 'email': return <FileText className="w-9 h-9 text-[#3b82f6]" />;
      case 'json': return <FileCode className="w-9 h-9 text-[#10b981]" />;
      case 'log': return <Database className="w-9 h-9 text-[#8b5cf6]" />;
      default: return <FileCode className="w-9 h-9 text-slate-400" />;
    }
  };

  const isDark = theme === 'dark';

  return (
    <div className="flex-1 flex flex-col lg:flex-row gap-6 h-full items-stretch font-mono">
      
      {/* File Explorer main area */}
      <div className={`flex-1 flex flex-col border rounded-2xl p-6 transition-colors duration-150 ${
        isDark ? 'bg-[#090d16] border-slate-800/80' : 'bg-white border-slate-200 shadow-sm'
      }`}>
        
        {/* Drive Path Breadcrumb */}
        <div className={`flex items-center space-x-2 text-xs border-b pb-4 mb-5 ${
          isDark ? 'text-slate-400 border-slate-900' : 'text-slate-900 border-slate-200'
        }`}>
          <HardDrive className={`w-4 h-4 ${isDark ? 'text-slate-500' : 'text-slate-600'}`} />
          <span className={`hover:text-kinetic-cyan cursor-pointer ${isDark ? 'text-slate-400' : 'text-slate-850 font-bold'}`}>My Drive</span>
          <ChevronRight className={`w-3 h-3 ${isDark ? 'text-slate-600' : 'text-slate-700'}`} />
          <span className={`hover:text-kinetic-cyan cursor-pointer ${isDark ? 'text-slate-400' : 'text-slate-855 font-bold'}`}>Overdrive Sync</span>
          <ChevronRight className={`w-3 h-3 ${isDark ? 'text-slate-600' : 'text-slate-700'}`} />
          <span className="text-kinetic-cyan font-bold">{activeFolder}</span>
        </div>

        {/* Directory Folders Row */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
          {['All', 'Deliverables', 'Drafts', 'Logs'].map(folder => (
            <button
              key={folder}
              onClick={() => {
                setActiveFolder(folder);
                setSelectedFile(null);
              }}
              className={`flex items-center space-x-3 p-3.5 rounded-xl border text-xs text-left transition-all duration-150 ${
                activeFolder === folder
                  ? isDark
                    ? 'bg-slate-950/70 border-kinetic-cyan/50 text-kinetic-cyan shadow-[0_0_12px_rgba(6,182,212,0.06)]'
                    : 'bg-cyan-50/50 border-kinetic-cyan/40 text-kinetic-cyan font-bold'
                  : isDark
                    ? 'bg-slate-950/20 border-slate-900 text-slate-400 hover:text-slate-200'
                    : 'bg-slate-50 border-slate-200 text-slate-800 hover:text-slate-950 hover:bg-slate-100/50 font-semibold'
              }`}
            >
              <Folder className={`w-4 h-4 ${activeFolder === folder ? 'text-kinetic-cyan' : isDark ? 'text-slate-400' : 'text-slate-700'}`} />
              <span className="uppercase tracking-wider">{folder}</span>
            </button>
          ))}
        </div>

        {/* Drag and Drop Upload Simulator Panel */}
        <div 
          onDragOver={(e) => { e.preventDefault(); setDragActive(true); }}
          onDragLeave={() => setDragActive(false)}
          onDrop={(e) => { e.preventDefault(); setDragActive(false); simulateUpload(); }}
          onClick={() => { if (!uploading) simulateUpload(); }}
          className={`mb-6 border border-dashed rounded-xl p-4 text-center cursor-pointer transition-all duration-150 flex flex-col items-center justify-center gap-1.5 ${
            uploading 
              ? isDark ? 'border-slate-800 bg-slate-950/20' : 'border-slate-300 bg-slate-50 shadow-inner'
              : dragActive
                ? 'border-kinetic-cyan bg-kinetic-cyan/5 text-kinetic-cyan shadow'
                : isDark 
                  ? 'border-slate-900 hover:border-slate-800 hover:bg-slate-950/10 text-slate-500 hover:text-slate-350' 
                  : 'border-slate-250 hover:border-slate-350 hover:bg-slate-50/80 text-slate-700 hover:text-slate-950 font-bold'
          }`}
        >
          {uploading ? (
            <div className="w-full max-w-sm space-y-2 font-mono text-[10px] view-fade-in">
              <div className="flex justify-between font-bold">
                <span className={isDark ? 'text-slate-300' : 'text-slate-950'}>Uploading: cs401_slides_final.pptx</span>
                <span className="text-kinetic-cyan font-bold">{uploadProgress}%</span>
              </div>
              <div className={`w-full h-1.5 rounded overflow-hidden ${isDark ? 'bg-slate-900' : 'bg-slate-200'}`}>
                <div 
                  className="h-full bg-kinetic-cyan transition-all duration-100" 
                  style={{ width: `${uploadProgress}%` }}
                />
              </div>
              <div className="text-[8px] uppercase tracking-wider text-slate-550 animate-pulse text-left">
                {uploadStep}
              </div>
            </div>
          ) : (
            <div className="flex flex-col items-center gap-1">
              <span className="text-[10px] uppercase tracking-widest font-black flex items-center gap-1.5 text-kinetic-cyan">
                <Upload className="w-3.5 h-3.5" /> Click or Drag & Drop to Upload Deliverables
              </span>
              <span className={`text-[8px] font-mono ${isDark ? 'text-slate-600' : 'text-slate-500'}`}>
                Supports pptx, eml, json, conf, logs (Max 10MB)
              </span>
            </div>
          )}
        </div>

        {/* Grid List of Files */}
        <div className="flex-grow overflow-y-auto max-h-[300px] lg:max-h-[none] pr-1">
          {filteredFiles.length === 0 ? (
            <div className={`text-center py-12 text-xs italic ${isDark ? 'text-slate-600' : 'text-slate-850 font-bold'}`}>
              No files found matching "{searchQuery}"
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
              {filteredFiles.map(file => (
                <div
                  key={file.id}
                  onClick={() => setSelectedFile(file)}
                  className={`p-4 rounded-xl border cursor-pointer flex flex-col justify-between transition-all duration-150 relative overflow-hidden group ${
                    selectedFile && selectedFile.id === file.id
                      ? isDark
                        ? 'bg-slate-950/60 border-kinetic-cyan/50 shadow-[0_0_15px_rgba(6,182,212,0.08)]'
                        : 'bg-cyan-50/20 border-kinetic-cyan/30 shadow-sm'
                      : isDark
                        ? 'bg-[#030712]/40 border-slate-900 hover:border-slate-800'
                        : 'bg-slate-50 border-slate-200 hover:border-slate-350 hover:bg-slate-100/30'
                  }`}
                >
                  {/* File Header Details */}
                  <div className="flex items-start justify-between">
                    <div className="flex items-center space-x-3.5">
                      {getFileIcon(file.type)}
                      <div>
                        <h4 className={`text-xs font-bold truncate max-w-[130px] group-hover:text-kinetic-cyan transition-colors ${
                          isDark ? 'text-slate-200' : 'text-slate-950 font-black'
                        }`} title={file.name}>
                          {file.name}
                        </h4>
                        <p className={`text-[9px] mt-1 uppercase tracking-widest ${isDark ? 'text-slate-500' : 'text-slate-800 font-bold'}`}>
                          {file.size} • {file.updated}
                        </p>
                      </div>
                    </div>
                  </div>

                  {/* File Footer Status */}
                  <div className={`border-t pt-3.5 mt-4 flex items-center justify-between text-[8px] tracking-wider uppercase font-semibold ${
                    isDark ? 'border-slate-900' : 'border-slate-200'
                  }`}>
                    <span className={isDark ? 'text-slate-500' : 'text-slate-800 font-bold'}>Folder: {file.folder}</span>
                    <span className={`px-2 py-0.5 rounded border ${
                      file.status === 'READY' || file.status === 'VERIFIED' || file.status === 'ACTIVE'
                        ? 'bg-cyber-emerald/5 border-cyber-emerald/25 text-cyber-emerald'
                        : file.status === 'TRIAGING'
                          ? 'bg-overdrive-crimson/5 border-overdrive-crimson/25 text-overdrive-crimson animate-pulse'
                          : 'bg-overdrive-amber/5 border-overdrive-amber/25 text-overdrive-amber animate-pulse'
                    }`}>
                      {file.status}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Right Details / Preview Panel */}
      <div className={`w-full lg:w-[360px] border rounded-2xl p-6 flex flex-col transition-colors duration-150 ${
        isDark ? 'bg-[#090d16] border-slate-800/80' : 'bg-white border-slate-200 shadow-sm'
      }`}>
        <h3 className={`text-xs font-bold uppercase tracking-widest border-b pb-4 mb-4 flex items-center gap-2 ${
          isDark ? 'text-slate-200 border-slate-900' : 'text-slate-950 border-slate-100'
        }`}>
          <Info className={`w-4 h-4 ${isDark ? 'text-slate-500' : 'text-slate-700'}`} />
          Document Preview
        </h3>

        {selectedFile ? (
          <div className="flex-1 flex flex-col justify-between h-full">
            <div className="space-y-4">
              <div>
                <h4 className={`text-xs font-bold truncate ${isDark ? 'text-slate-350 font-bold' : 'text-slate-950'}`}>{selectedFile.name}</h4>
                <p className={`text-[9px] uppercase mt-1 ${isDark ? 'text-slate-500' : 'text-slate-800 font-bold'}`}>
                  TYPE: {selectedFile.type.toUpperCase()} • SIZE: {selectedFile.size}
                </p>
              </div>

              {/* Document Text Body */}
              <div className={`p-4 rounded-xl border text-[10px] leading-normal overflow-y-auto max-h-[220px] lg:max-h-[300px] whitespace-pre-wrap font-mono ${
                isDark 
                  ? 'bg-slate-950/60 border-slate-900 text-slate-400' 
                  : 'bg-slate-50 border-slate-200 text-slate-950 font-bold'
              }`}>
                {selectedFile.content}
              </div>
            </div>

            <div className="flex space-x-3.5 mt-5">
              <button 
                onClick={() => alert(`Downloading deliverable: ${selectedFile.name}`)}
                className={`flex-1 flex items-center justify-center space-x-2 text-[10px] font-bold uppercase py-3 rounded-lg border transition-all duration-150 active:scale-97 ${
                  isDark 
                    ? 'border-slate-850 bg-slate-950/45 hover:border-slate-700 text-slate-300' 
                    : 'border-slate-250 bg-slate-50 hover:border-slate-350 text-slate-850 hover:bg-slate-100/50'
                }`}
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download</span>
              </button>
              <button 
                onClick={() => alert(`Opening web link inside Workspace for: ${selectedFile.name}`)}
                className={`flex-none p-3 rounded-lg border transition-all duration-150 active:scale-97 ${
                  isDark 
                    ? 'border-slate-850 bg-slate-950/45 hover:border-slate-700 text-slate-400 hover:text-kinetic-cyan' 
                    : 'border-slate-250 bg-slate-50 hover:border-slate-350 text-slate-850 hover:text-kinetic-cyan hover:bg-slate-100/50'
                }`}
                title="Open in Workspace"
              >
                <ExternalLink className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>
        ) : (
          <div className={`flex-1 flex flex-col items-center justify-center text-center p-8 border border-dashed rounded-xl text-xs italic ${
            isDark ? 'border-slate-900 text-slate-500' : 'border-slate-250 text-slate-850 font-bold'
          }`}>
            <Clock className={`w-6 h-6 mb-3 ${isDark ? 'text-slate-750' : 'text-slate-600'}`} />
            Select a generated draft deliverable to view its layout rules and compiled content.
          </div>
        )}
      </div>
    </div>
  );
}
